{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "144959a2",
   "metadata": {},
   "source": [
    "# Workshop 11 â€“ OOP with Car & Vehicle\n",
    "\n",
    "This notebook follows the **Car / Vehicle activities** from the Week 11 slides.\n",
    "\n",
    "**Learning goals**\n",
    "\n",
    "By the end of this notebook you should be able to:\n",
    "\n",
    "- Define a simple Python class (`Car`)\n",
    "- Use a constructor (`__init__`) and the `self` keyword\n",
    "- Add attributes and methods to a class\n",
    "- Use **encapsulation** with private attributes and accessor methods (getters)\n",
    "- Create a `Vehicle` base class and a `Car` subclass using **inheritance**\n",
    "- Override `__str__` to make objects printable"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "59a6711c",
   "metadata": {},
   "source": [
    "---\n",
    "## 1. Warm-up: a very simple `Car` class\n",
    "\n",
    "This is a **first version** of a `Car` class with *public* attributes.\n",
    "\n",
    "### Task 1.1\n",
    "\n",
    "1. Run the cell below.\n",
    "2. Change some values for `car1` and `car2` and run it again."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "81328d80",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "class Car:\n",
    "    \"\"\"A very simple Car class with public attributes.\"\"\"\n",
    "\n",
    "    def __init__(self, make, model, year, fuel_type):\n",
    "        self.make = make\n",
    "        self.model = model\n",
    "        self.year = year\n",
    "        self.fuel_type = fuel_type\n",
    "\n",
    "\n",
    "# Create a couple of cars (instances)\n",
    "car1 = Car(\"Audi\", \"A3\", 2020, \"petrol\")\n",
    "car2 = Car(\"Volvo\", \"XC40\", 2021, \"diesel\")\n",
    "\n",
    "# Access their data using dot notation\n",
    "print(\"Car 1:\", car1.make, car1.model, car1.year, car1.fuel_type)\n",
    "print(\"Car 2:\", car2.make, car2.model, car2.year, car2.fuel_type)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "393ce829",
   "metadata": {},
   "source": [
    "---\n",
    "## 2. Encapsulation: make attributes **private**\n",
    "\n",
    "In the slides, you are asked to:\n",
    "\n",
    "> Change the make, year, model, and fuel type into private attributes and create accessor methods to be able to get the data.\n",
    "\n",
    "We will now **refactor** the `Car` class so that:\n",
    "\n",
    "- All attributes become **private** (`__make`, `__model`, `__year`, `__fuel_type`)\n",
    "- We add **accessor methods** (getters):\n",
    "  - `get_make()`\n",
    "  - `get_model()`\n",
    "  - `get_year()`\n",
    "  - `get_fuel_type()`\n",
    "\n",
    "### Task 2.1\n",
    "\n",
    "1. Complete the `TODO` sections in the `Car` class.\n",
    "2. Run the test code at the bottom."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dfd7706e",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "class Car:\n",
    "    \"\"\"Represents a car with private attributes and accessor methods.\n",
    "\n",
    "    Attributes (all private):\n",
    "        __make (str)\n",
    "        __model (str)\n",
    "        __year (int)\n",
    "        __fuel_type (str)\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, make, model, year, fuel_type):\n",
    "        # TODO: store all attributes as *private* (double underscore)\n",
    "        # Example: self.__make = make\n",
    "        self.__make = make\n",
    "        self.__model = model\n",
    "        self.__year = year\n",
    "        self.__fuel_type = fuel_type\n",
    "\n",
    "    # TODO: create accessor (getter) methods for each attribute\n",
    "\n",
    "    def get_make(self):\n",
    "        return self.__make\n",
    "\n",
    "    def get_model(self):\n",
    "        return self.__model\n",
    "\n",
    "    def get_year(self):\n",
    "        return self.__year\n",
    "\n",
    "    def get_fuel_type(self):\n",
    "        return self.__fuel_type\n",
    "\n",
    "\n",
    "# --- Test the class ---\n",
    "car_audi = Car(\"Audi\", \"A3\", 2020, \"petrol\")\n",
    "car_volvo = Car(\"Volvo\", \"XC40\", 2021, \"diesel\")\n",
    "\n",
    "print(\"Audi make:\", car_audi.get_make())\n",
    "print(\"Volvo fuel type:\", car_volvo.get_fuel_type())\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "36c0ef74",
   "metadata": {},
   "source": [
    "---\n",
    "## 3. Adding methods and `__str__`\n",
    "\n",
    "To make our objects more useful and easier to debug, we'll add:\n",
    "\n",
    "- A **docstring** to document the class\n",
    "- Some **methods**, e.g. `is_electric()`\n",
    "- A `__str__` method to control how the object is printed\n",
    "\n",
    "### Task 3.1\n",
    "\n",
    "1. Add a method `is_electric(self)` that returns `True` if `fuel_type` is `\"electric\"`.\n",
    "2. Add a `__str__(self)` method that returns something like:\n",
    "   - `\"2020 Audi A3 (petrol)\"`\n",
    "3. Run the test code at the bottom."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a8ce862e",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "class Car:\n",
    "    \"\"\"Represents a car in the system.\n",
    "\n",
    "    Attributes (private):\n",
    "        __make (str): Car manufacturer (e.g. 'Audi')\n",
    "        __model (str): Car model (e.g. 'A3')\n",
    "        __year (int): Production year\n",
    "        __fuel_type (str): Fuel type (e.g. 'petrol', 'diesel', 'electric')\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, make, model, year, fuel_type):\n",
    "        self.__make = make\n",
    "        self.__model = model\n",
    "        self.__year = year\n",
    "        self.__fuel_type = fuel_type\n",
    "\n",
    "    # Accessor methods\n",
    "    def get_make(self):\n",
    "        return self.__make\n",
    "\n",
    "    def get_model(self):\n",
    "        return self.__model\n",
    "\n",
    "    def get_year(self):\n",
    "        return self.__year\n",
    "\n",
    "    def get_fuel_type(self):\n",
    "        return self.__fuel_type\n",
    "\n",
    "    # TODO: implement this method\n",
    "    def is_electric(self):\n",
    "        \"\"\"Return True if this car is electric.\"\"\"\n",
    "        return self.__fuel_type.lower() == \"electric\"\n",
    "\n",
    "    # TODO: implement __str__\n",
    "    def __str__(self):\n",
    "        \"\"\"User-friendly string representation of the car.\"\"\"\n",
    "        return f\"{self.__year} {self.__make} {self.__model} ({self.__fuel_type})\"\n",
    "\n",
    "\n",
    "# --- Test the class ---\n",
    "car1 = Car(\"Audi\", \"A3\", 2020, \"petrol\")\n",
    "car2 = Car(\"Tesla\", \"Model 3\", 2023, \"electric\")\n",
    "\n",
    "print(car1)  # should use __str__\n",
    "print(car2)  # should use __str__\n",
    "\n",
    "print(\"Is car1 electric?\", car1.is_electric())\n",
    "print(\"Is car2 electric?\", car2.is_electric())\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0fb0ede7",
   "metadata": {},
   "source": [
    "---\n",
    "## 4. Inheritance: `Vehicle` (base class) and `Car` (subclass)\n",
    "\n",
    "In the slides you saw examples of **inheritance** using `Animal`, `Dog`, and `Cat`.\n",
    "We'll now do a similar thing with `Vehicle` and `Car`:\n",
    "\n",
    "- `Vehicle` will be a **general** class for any vehicle.\n",
    "- `Car` will be a **specialised** type of `Vehicle`.\n",
    "\n",
    "### Design\n",
    "\n",
    "- Class `Vehicle`:\n",
    "  - Private attributes: `__make`, `__model`, `__year`, `__fuel_type`\n",
    "  - Methods: getters + `__str__`\n",
    "- Class `Car(Vehicle)`:\n",
    "  - Extra attribute: `__num_doors`\n",
    "  - Uses `super().__init__(...)` to call the base constructor\n",
    "  - Overrides `__str__` to include number of doors\n",
    "\n",
    "### Task 4.1\n",
    "\n",
    "1. Complete the `Vehicle` and `Car` classes.\n",
    "2. Run the test code at the bottom."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "565c7ad0",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "class Vehicle:\n",
    "    \"\"\"Represents a generic vehicle.\"\"\"\n",
    "\n",
    "    def __init__(self, make, model, year, fuel_type):\n",
    "        self.__make = make\n",
    "        self.__model = model\n",
    "        self.__year = year\n",
    "        self.__fuel_type = fuel_type\n",
    "\n",
    "    def get_make(self):\n",
    "        return self.__make\n",
    "\n",
    "    def get_model(self):\n",
    "        return self.__model\n",
    "\n",
    "    def get_year(self):\n",
    "        return self.__year\n",
    "\n",
    "    def get_fuel_type(self):\n",
    "        return self.__fuel_type\n",
    "\n",
    "    def __str__(self):\n",
    "        return f\"{self.__year} {self.__make} {self.__model} ({self.__fuel_type})\"\n",
    "\n",
    "\n",
    "class Car(Vehicle):\n",
    "    \"\"\"A car is a specific type of Vehicle.\"\"\"\n",
    "\n",
    "    def __init__(self, make, model, year, fuel_type, num_doors):\n",
    "        # TODO: call the Vehicle constructor\n",
    "        super().__init__(make, model, year, fuel_type)\n",
    "        # store extra attribute\n",
    "        self.__num_doors = num_doors\n",
    "\n",
    "    def get_num_doors(self):\n",
    "        return self.__num_doors\n",
    "\n",
    "    def __str__(self):\n",
    "        # TODO: extend parent __str__ with door information\n",
    "        base = super().__str__()\n",
    "        return f\"{base} â€“ Car with {self.__num_doors} doors\"\n",
    "\n",
    "\n",
    "# --- Test the inheritance ---\n",
    "generic_vehicle = Vehicle(\"GenericMake\", \"ModelX\", 2018, \"hybrid\")\n",
    "audi_car = Car(\"Audi\", \"A3\", 2020, \"petrol\", num_doors=4)\n",
    "\n",
    "print(generic_vehicle)\n",
    "print(audi_car)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e1309261",
   "metadata": {},
   "source": [
    "---\n",
    "## 5. Polymorphism (optional)\n",
    "\n",
    "*Polymorphism* means we can treat different subclasses as if they are the same base type.\n",
    "\n",
    "Here we will:\n",
    "\n",
    "- Create several `Vehicle` and `Car` objects\n",
    "- Put them all into **one list**\n",
    "- Loop over the list and `print()` each object\n",
    "  - Python will automatically call the correct `__str__` method.\n",
    "\n",
    "### Task 5.1\n",
    "\n",
    "1. Create at least 1 `Vehicle` and 2 `Car` objects.\n",
    "2. Add them to the `vehicles` list.\n",
    "3. Run the loop and observe the output."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c9a83876",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# TODO: create some vehicles and cars\n",
    "v1 = Vehicle(\"Volvo\", \"Bus7700\", 2015, \"diesel\")\n",
    "c1 = Car(\"Tesla\", \"Model 3\", 2023, \"electric\", 4)\n",
    "c2 = Car(\"Volkswagen\", \"Golf\", 2019, \"petrol\", 5)\n",
    "\n",
    "vehicles = [v1, c1, c2]\n",
    "\n",
    "for vehicle in vehicles:\n",
    "    print(vehicle)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "345a6998",
   "metadata": {},
   "source": [
    "---\n",
    "## 6. Reflection (write your answers here)\n",
    "\n",
    "In **your own words**, answer the following questions **inside this cell**:\n",
    "\n",
    "1. What is the difference between a *class* and an *object*?\n",
    "2. Why do we make attributes private and use getter methods?\n",
    "3. What is the relationship between `Vehicle` and `Car`?\n",
    "4. Where did you see polymorphism in this notebook?"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}